# Generated by Django 3.0.7 on 2020-07-25 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdjex',
            name='posRatings',
            field=models.ManyToManyField(blank=True, related_name='your_posRatings', through='content_users.Junct_Rate_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
