# Generated by Django 3.0.7 on 2020-07-25 01:11

import content_phylums.models._ccpick
import content_phylums.models._deck
import content_phylums.models._format
import content_phylums.models._groupdeck
import content_phylums.models._note
import content_phylums.models._phylum_tag
import content_phylums.models.junct_img_ccpick
import content_phylums.models.junct_img_note
import content_phylums.models.junct_snd_note
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ccpick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isPublished', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_phylums.models._ccpick.Ccpick.upload_media, width_field='url_width')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isPublished', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_phylums.models._deck.Deck.upload_media, width_field='url_width')),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isPublished', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_phylums.models._format.Format.upload_media, width_field='url_width')),
                ('content_type', models.CharField(choices=[('DECK', 'Deck'), ('GROUPDECK', 'Groupdeck'), ('LESSON', 'Lesson')], default='DECK', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Groupdeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isPublished', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_phylums.models._groupdeck.Groupdeck.upload_media, width_field='url_width')),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Img_Ccpick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_phylums.models.junct_img_ccpick.Junct_Img_Ccpick.upload_media, width_field='url_width')),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Img_Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_phylums.models.junct_img_note.Junct_Img_Note.upload_media, width_field='url_width')),
            ],
        ),
        migrations.CreateModel(
            name='Junct_PhylumTag_Ccpick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Junct_PhylumTag_Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Junct_PhylumTag_Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Junct_PhylumTag_Groupdeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Junct_PhylumTag_Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Rate_Ccpick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posRating', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Rate_Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posRating', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Rate_Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posRating', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Rate_Groupdeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posRating', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Rate_Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posRating', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Rev_Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('stars', models.SmallIntegerField(default=3)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Rev_Groupdeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('stars', models.SmallIntegerField(default=3)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Rev_Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('stars', models.SmallIntegerField(default=3)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Snd_Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snd', models.FileField(blank=True, null=True, upload_to=content_phylums.models.junct_snd_note.Junct_Snd_Note.upload_media)),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Sub_Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Sub_Groupdeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Sub_Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phylum_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_phylums.models._phylum_tag.Phylum_Tag.upload_media, width_field='url_width')),
                ('isPublished', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('note_contents', models.TextField(blank=True, null=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isPublished', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_phylums.models._note.Note.upload_media, width_field='url_width')),
                ('format_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format_note', to='content_phylums.Format')),
            ],
        ),
    ]
