# Generated by Django 3.0.7 on 2020-07-25 18:30

import content_phylums.models._ccpick
import content_phylums.models._deck
import content_phylums.models._format
import content_phylums.models._groupdeck
import content_phylums.models._note
import content_phylums.models._phylum_tag
import content_phylums.models.junct_img_ccpick
import content_phylums.models.junct_img_note
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_phylums', '0002_auto_20200724_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccpick',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=content_phylums.models._ccpick.Ccpick.upload_media),
        ),
        migrations.AlterField(
            model_name='deck',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=content_phylums.models._deck.Deck.upload_media),
        ),
        migrations.AlterField(
            model_name='format',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=content_phylums.models._format.Format.upload_media),
        ),
        migrations.AlterField(
            model_name='groupdeck',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=content_phylums.models._groupdeck.Groupdeck.upload_media),
        ),
        migrations.AlterField(
            model_name='junct_img_ccpick',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=content_phylums.models.junct_img_ccpick.Junct_Img_Ccpick.upload_media),
        ),
        migrations.AlterField(
            model_name='junct_img_note',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=content_phylums.models.junct_img_note.Junct_Img_Note.upload_media),
        ),
        migrations.AlterField(
            model_name='note',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=content_phylums.models._note.Note.upload_media),
        ),
        migrations.AlterField(
            model_name='phylum_tag',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=content_phylums.models._phylum_tag.Phylum_Tag.upload_media),
        ),
    ]
