# Generated by Django 3.0.7 on 2020-08-03 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_phylums', '0003_auto_20200725_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Junct_Sub_Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subbedFormat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subbedFormat', to='content_phylums.Format')),
                ('subbingUser_Format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subbingUser_Format', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('subbingUser_Format', 'subbedFormat')},
            },
        ),
        migrations.AddField(
            model_name='format',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='format_subscriptions', through='content_phylums.Junct_Sub_Format', to=settings.AUTH_USER_MODEL),
        ),
    ]
