# Generated by Django 3.0.7 on 2020-08-07 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_phylums', '0004_auto_20200803_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junct_snd_note',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_snd', to='content_phylums.Note'),
        ),
    ]
