# Generated by Django 3.0.7 on 2020-08-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_phylums', '0005_auto_20200806_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='junct_img_ccpick',
            name='name',
            field=models.CharField(default='No_Name', max_length=50),
        ),
        migrations.AddField(
            model_name='junct_img_note',
            name='name',
            field=models.CharField(default='No_Name', max_length=50),
        ),
        migrations.AddField(
            model_name='junct_snd_note',
            name='name',
            field=models.CharField(default='No_Name', max_length=50),
        ),
    ]
