# Generated by Django 3.0.7 on 2020-07-25 01:11

import content_informatics.models._addon
import content_informatics.models._deed
import content_informatics.models._informatics_tag
import content_informatics.models._theme
import content_informatics.models.junct_img_addon
import content_informatics.models.junct_img_feedback
import content_informatics.models.junct_img_news
import content_informatics.models.junct_img_theme
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('isPublished', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_informatics.models._addon.Addon.upload_media, width_field='url_width')),
            ],
        ),
        migrations.CreateModel(
            name='Deed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_duration', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('isPublished', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_informatics.models._deed.Deed.upload_media, width_field='url_width')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('topic', models.CharField(choices=[('CCPICK', 'Ccpick'), ('DECK', 'Deck'), ('FORMAT', 'Format'), ('GEN_APK', 'General for mobile app'), ('GEN_EXE', 'General for desktop app'), ('GEN_WEB', 'General for website'), ('GROUPDECK', 'Groupdeck'), ('NOTE', 'Note'), ('STORE', 'Store'), ('USER', 'User')], default='DECK', max_length=22)),
                ('defcon', models.CharField(choices=[('POSITIVE', 'Positive'), ('HELP', 'Help'), ('BUG', 'Bug'), ('CRASH', 'Crash'), ('DANGER', 'Danger')], default='BUG', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isPublished', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Informatics_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_informatics.models._informatics_tag.Informatics_Tag.upload_media, width_field='url_width')),
                ('isPublished', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Img_Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_informatics.models.junct_img_addon.Junct_Img_Addon.upload_media, width_field='url_width')),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Img_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_informatics.models.junct_img_feedback.Junct_Img_Feedback.upload_media, width_field='url_width')),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Img_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_informatics.models.junct_img_news.Junct_Img_News.upload_media, width_field='url_width')),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Img_Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_informatics.models.junct_img_theme.Junct_Img_Theme.upload_media, width_field='url_width')),
            ],
        ),
        migrations.CreateModel(
            name='Junct_InformaticsTag_Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Junct_InformaticsTag_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Junct_InformaticsTag_Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Sub_Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Junct_Sub_Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Junct_User_Deed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_start', models.DateTimeField(auto_now_add=True)),
                ('dt_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isPublished', models.BooleanField(default=False)),
                ('topic', models.CharField(choices=[('FIX', 'Fix'), ('UPDATE', 'Update'), ('NEW_FEATURE', 'New Feature')], default='UPDATE', max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('isPublished', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, height_field='url_height', null=True, upload_to=content_informatics.models._theme.Theme.upload_media, width_field='url_width')),
            ],
        ),
    ]
