# Generated by Django 3.0.7 on 2020-07-25 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_informatics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='junct_user_deed',
            name='deed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deed_holder', to='content_informatics.Deed'),
        ),
        migrations.AddField(
            model_name='junct_user_deed',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_deed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='junct_sub_theme',
            name='subbedTheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subbedTheme', to='content_informatics.Theme'),
        ),
        migrations.AddField(
            model_name='junct_sub_theme',
            name='subbingUser_Theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subbingUser_Theme', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='junct_sub_addon',
            name='subbedAddon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subbedAddon', to='content_informatics.Addon'),
        ),
        migrations.AddField(
            model_name='junct_sub_addon',
            name='subbingUser_Addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subbingUser_Addon', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='junct_informaticstag_theme',
            name='tagged_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_theme', to='content_informatics.Theme'),
        ),
        migrations.AddField(
            model_name='junct_informaticstag_theme',
            name='theme_informatics_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_informatics_tag', to='content_informatics.Informatics_Tag'),
        ),
        migrations.AddField(
            model_name='junct_informaticstag_news',
            name='news_informatics_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_informatics_tag', to='content_informatics.Informatics_Tag'),
        ),
        migrations.AddField(
            model_name='junct_informaticstag_news',
            name='tagged_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_news', to='content_informatics.News'),
        ),
        migrations.AddField(
            model_name='junct_informaticstag_addon',
            name='addon_informatics_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Addon_informatics_tag', to='content_informatics.Informatics_Tag'),
        ),
        migrations.AddField(
            model_name='junct_informaticstag_addon',
            name='tagged_addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_addon', to='content_informatics.Addon'),
        ),
        migrations.AddField(
            model_name='junct_img_theme',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_img', to='content_informatics.Theme'),
        ),
        migrations.AddField(
            model_name='junct_img_news',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_img', to='content_informatics.News'),
        ),
        migrations.AddField(
            model_name='junct_img_feedback',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_img', to='content_informatics.Feedback'),
        ),
        migrations.AddField(
            model_name='junct_img_addon',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_img', to='content_informatics.Addon'),
        ),
        migrations.AddField(
            model_name='feedback_response',
            name='feedback_response_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_response_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback_response',
            name='ori_feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_response', to='content_informatics.Feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='junct_sub_theme',
            unique_together={('subbingUser_Theme', 'subbedTheme')},
        ),
        migrations.AlterUniqueTogether(
            name='junct_sub_addon',
            unique_together={('subbingUser_Addon', 'subbedAddon')},
        ),
        migrations.AlterUniqueTogether(
            name='junct_informaticstag_theme',
            unique_together={('tagged_theme', 'theme_informatics_tag')},
        ),
        migrations.AlterUniqueTogether(
            name='junct_informaticstag_news',
            unique_together={('tagged_news', 'news_informatics_tag')},
        ),
        migrations.AlterUniqueTogether(
            name='junct_informaticstag_addon',
            unique_together={('tagged_addon', 'addon_informatics_tag')},
        ),
    ]
