# Generated by Django 3.0.7 on 2020-07-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_informatics', '0003_auto_20200725_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informatics_tag',
            old_name='img',
            new_name='icon',
        ),
    ]
