# Generated by Django 3.0.7 on 2020-08-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_informatics', '0004_auto_20200725_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junct_img_feedback',
            name='img',
        ),
        migrations.RemoveField(
            model_name='junct_img_feedback',
            name='owner',
        ),
        migrations.AddField(
            model_name='junct_img_feedback',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='junct_img_feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='junct_img_feedback',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
