# Generated by Django 3.0.7 on 2020-08-08 15:49

import content_informatics.models.junct_img_feedback
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_informatics', '0005_auto_20200807_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junct_img_feedback',
            name='content',
        ),
        migrations.RemoveField(
            model_name='junct_img_feedback',
            name='image',
        ),
        migrations.RemoveField(
            model_name='junct_img_feedback',
            name='title',
        ),
        migrations.AddField(
            model_name='junct_img_feedback',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=content_informatics.models.junct_img_feedback.Junct_Img_Feedback.upload_media),
        ),
        migrations.AddField(
            model_name='junct_img_feedback',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_img', to='content_informatics.Feedback'),
            preserve_default=False,
        ),
    ]
