# Generated by Django 3.0.7 on 2020-08-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_informatics', '0006_auto_20200808_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='junct_img_addon',
            name='name',
            field=models.CharField(default='No_Name', max_length=50),
        ),
        migrations.AddField(
            model_name='junct_img_feedback',
            name='name',
            field=models.CharField(default='No_Name', max_length=50),
        ),
        migrations.AddField(
            model_name='junct_img_news',
            name='name',
            field=models.CharField(default='No_Name', max_length=50),
        ),
        migrations.AddField(
            model_name='junct_img_theme',
            name='name',
            field=models.CharField(default='No_Name', max_length=50),
        ),
    ]
