# Generated by Django 3.0.7 on 2020-08-12 18:47

import content_informatics.models.junct_img_feedback_response
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_informatics', '0007_auto_20200808_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Junct_Img_Feedback_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No_Name', max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to=content_informatics.models.junct_img_feedback_response.Junct_Img_Feedback_Response.upload_media)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_response_img', to='content_informatics.Feedback_Response')),
            ],
        ),
    ]
